version: '2'
services:
  # Node
  node:
    hostname: crispy-node
    image: crispy-node
    ports:
      - "127.0.0.1:3000:3000"
    container_name: crispy-node-server
    links:
      - db
    environment:
      - VIRTUAL_HOST=crispy.docker

  # MongoDB
  db:
    hostname: crispy-mongodb
    image: mongo:3.3.15
    ports:
      - "127.0.0.1:27017:32768"
    container_name: crispy-mongo
    # DB configuration
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=crispy
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=crispy
