version: '2'
services:
  # Node
  node:
    hostname: crispy-node
    image: node:6.7
    ports:
      #- "192.168.99.100:80:80"
      #- "192.168.99.100:443:443"
    volumes:
      # Docroot mapping
      - "./public:/var/www/html"
    links:
      - db
    environment:
        - VIRTUAL_HOST=crispy.docker

  # MongoDB
  db:
    hostname: crispy-mongodb
    image: mongo:3.3.15
    ports:
      - "192.168.99.100:27017:32768"
    # DB configuration
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=crispy
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=crispy
    #volumes:
       # MySQL configuration overrides
       #- "./.docker/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"